### ISSUE TITLE
Payload is not converted to JSON

### ISSUE THREAD

**Issue by JanBukva** [nittro/page#1]
Hi,
I have been trying out Nittro and found a bug. The payload Nette sends is kept as a string (even though it has the correct HTTP header "Content-Type:application/json;") and thus not doing anything except playing animations.

I'm running PHP7, latest dev nette (with your nittro/nette) and bower packages and the problem is occurring in all browsers I have installed (Chrome, Firefox, IE)

Here is the problematic part (might be somewhere else)
Nittro/Ajax/Service.js @ 280
```js
if (typeof payload !== 'object' || !payload) {
    this._cleanup();
    return null;
}
```

I fixed it by adding this before
```js
if(typeof payload === 'string') payload = JSON.parse(payload);
```

**Comment by jahudka** [comment]
Hi, thanks for the report, but are you *absolutely* sure you're sending the correct Content-Type header? Because parsing the response text as JSON based on the Content-Type header is something NIttro already does, see `src/js/Nittro/Ajax/Transport/Native.js`, line 195.

The fact that the payload is a string and not an object by the time it reaches the Page service means that the Page service shouldn't process it, period. So your fix is not a *fix*, it's a *hack* :-P

Is it possible that you're maybe attaching a charset to the Content-Type header? As in, `Content-Type: application/json; charset=utf-8`? Because that would be invalid: there is no "charset" parameter for the application/json content type. Moreover, JSON must, by it's very definition, always be Unicode, so the charset parameter would be redundant. It's all mentioned in the answers [here](http://stackoverflow.com/questions/9254891/what-does-content-type-application-json-charset-utf-8-really-mean).

**Comment by JanBukva** [comment]
Yes I do have "Content-Type: text/html; charset=utf-8" as it is being sent by Nette itself

JsonResponse @ 62
```php
public function send(Nette\Http\IRequest $httpRequest, Nette\Http\IResponse $httpResponse)
	{
		$httpResponse->setContentType($this->contentType, 'utf-8');
		echo Nette\Utils\Json::encode($this->payload);
	}
```

**Comment by jahudka** [comment]
Well then that's a bug in Nette, not Nittro, isn't it? :-) I'll see what can be done..

**Comment by JanBukva** [comment]
Well, I guess so :)
but when Nittro is meant to be used with Nette, it should probably also work with this not so correct header.
Thanks anyway

**Comment by jahudka** [comment]
That's true and I'll change the code to be less strict of course, but I am freakin' pissed off.. What's the point of trying to follow standards and specs if nobody around you even tries to do it too?

This is quite a recent change in Nette code by the way, it's only [14 days](https://github.com/nette/application/issues/120) since this behaviour was introduced, so maybe it can still be fixed..

**Comment by jahudka** [comment]
Okay, try updating to v1.9.4, that should help..

**Comment by JanBukva** [comment]
Yes that helped, thank you
